SET POSTGRES_URL=localhost:5432
SET POSTGRES_USER=postgres
SET POSTGRES_PW=admin
SET POSTGRES_DB=movie_info
SET FLASK_ENV=development
SET SQLALCHEMY_TRACK_MODIFICATIONS=False
SET SQLALCHEMY_ECHO=True
SET FLASK_APP=wsgi